name = "spkr"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = false
routes = [{ pattern = "eval.work", custom_domain = true }]

[assets]
directory = "public"

[env.beta]
routes = [{ pattern = "beta.eval.work", custom_domain = true }]
